### ISSUE TITLE
Suggested Improvement to documentation

### ISSUE THREAD

**Issue by esandoval30** [arthurimirzian/salesforce-jwt-bearer-token-flow#1]
It'd be useful to mention in your usage example that the aud parameter must be set to https://login.salesforce.com or https://test.salesforce.com 

Salesforce is very clear in the AWT Flow documentation that aud should be one of the above but from someone using your package for the 1st time, it may not be obvious.... and the errors generated by this package, if no or a wrong aud parameter value is supplied, do not provide helpful messages

**Comment by arthurimirzian** [comment]
The audience (aud) must be:
- https://login.salesforce.com,
- https://test.salesforce.com
- **https://acme.force.com/customers (where acme.force.com/customers is your community URL)**

**Comment by esandoval30** [comment]
That's correct and it is documented by Salesforce https://help.salesforce.com/articleView?id=remoteaccess_oauth_jwt_flow.htm&type=5

I am only suggesting that you update the README to provide a hint to fill in the audience (aud) parameter...

**Comment by arthurimirzian** [comment]
Ok, just updated the the ReadMe.
