### ISSUE TITLE
 The engine "node" is incompatible with this module. Expected version "0.12.7". Got "12.16.0"

### ISSUE THREAD

**Issue by whyman** [arthurimirzian/salesforce-jwt-bearer-token-flow#5]
When trying to install on `node:lts-alpine` with yarn

```
The engine "node" is incompatible with this module. Expected version "0.12.7". Got "12.16.0"
```

0.12.7 doesn't look right?

**Comment by whyman** [comment]
Also in npm `npm WARN notsup Unsupported engine for salesforce-jwt-bearer-token-flow@0.2.3: wanted: {"node":"0.12.7"} (current: {"node":"12.16.0","npm":"6.13.4"})`

**Comment by whyman** [comment]
bump

**Comment by arthurimirzian** [comment]
I fixed the issue by updating the package.json.
Thanks
